server:
  port: 7050

spring:
  application:
    name: securityGateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: forenoon
            uri: lb://forenoon
            predicates:
              - Path=/forenoon/**
            filters:
              - StripPrefix=1
          - id: afternoon
            uri: lb://afternoon
            predicates:
              - Path=/afternoon/**
            filters:
              - StripPrefix=1
          - id: notify
            uri: lb://notify
            predicates:
              - Path=/notify/**
            filters:
              - StripPrefix=1
  datasource:
    url: jdbc:postgresql://localhost:5432/capstone
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/